name: Release

on:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build - ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- NATIVE LINUX
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
            use_cross: false

          # --- CROSS-COMPILED LINUX & FREEBSD
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu # Linux ARM64
            archive: tar.gz
            use_cross: true
          - os: ubuntu-22.04
            target: armv7-unknown-linux-gnueabihf # Linux ARM 32-bit
            archive: tar.gz
            use_cross: true
          - os: ubuntu-22.04
            target: i686-unknown-linux-gnu # Linux 32-bit (x86)
            archive: tar.gz
            use_cross: true
          - os: ubuntu-22.04
            target: x86_64-unknown-freebsd # FreeBSD
            archive: tar.gz
            use_cross: true

          # --- MAC OS
          - os: macos-13 # Intel Mac
            target: x86_64-apple-darwin
            archive: tar.gz
            use_cross: false
          - os: macos-14 # Apple Silicon Mac
            target: aarch64-apple-darwin
            archive: tar.gz
            use_cross: false

          # --- WINDOWS
          - os: windows-latest
            target: x86_64-pc-windows-msvc # Windows x64
            archive: zip
            use_cross: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc # Windows ARM64
            archive: zip
            use_cross: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}, wasm32-wasip1

      - name: Install Cross (for cross-compilation)
        if: matrix.use_cross == true
        uses: taiki-e/install-action@cross

      - name: Build Compiler (Native)
        if: matrix.use_cross == false
        run: cargo build --release --target ${{ matrix.target }} --manifest-path cli/Cargo.toml

      - name: Build Compiler (Cross)
        if: matrix.use_cross == true
        run: cross build --release --target ${{ matrix.target }} --manifest-path cli/Cargo.toml

      - name: Build Standard Library (WASI)
        run: cargo build --release --target wasm32-wasip1 --manifest-path stdlib/rust/Cargo.toml

      - name: Package (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p release_pkg/bin
          mkdir -p release_pkg/std

          # 1. Copy compiler frontend and rename 'wasome'
          # TODO: Should it be called waso instead??
          cp cli/target/${{ matrix.target }}/release/waso release_pkg/bin/wasome

          # 2. Copy the pure Wasome std
          cp -r stdlib/wasome/* release_pkg/std/

          # 3. Copy the rust bindings for the std
          cp stdlib/rust/target/wasm32-wasip1/release/libstdlib.a release_pkg/std/

          # Compress
          cd release_pkg
          tar -czvf ../wasome-${{ matrix.target }}.tar.gz *

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release_pkg\bin
          New-Item -ItemType Directory -Force -Path release_pkg\std

          # 1. Copy compiler frontend and rename 'wasome.exe'
          # TODO: Should it be called waso instead??
          Copy-Item cli\target\${{ matrix.target }}\release\waso.exe release_pkg\bin\wasome.exe

          # 2. Copy the pure Wasome std
          Copy-Item -Recurse stdlib\wasome\* release_pkg\std\

          # 3. Copy the rust bindings for the std
          Copy-Item stdlib\rust\target\wasm32-wasip1\release\libstdlib.a release_pkg\std\

          # Compress
          Compress-Archive -Path release_pkg\* -DestinationPath wasome-${{ matrix.target }}.zip

      - name: Upload Artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: wasome-${{ matrix.target }}.${{ matrix.archive }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
